### PR TITLE
Upgrade to GPT4

### PR DESCRIPTION
**Pull request by akfaew**
Seems to work :)

### CODE REVIEW

**Comment by edofic** [comment]
I'm still on the waitlist so I'd really like to keep 3.5 😄 We could make this into a param but it's not really ergonomic. Any ideas ?

**Comment by edofic** [comment]
@akfaew I pushed changes to support setting the model via env (just like for the api key) as I just got access to gpt-4 via Azure and I'll be adding that next. Closing this for now, let me know if you have any better ideas.

**Comment by akfaew** [comment]
Sounds good. It's weird, I have a free account and GPT-4 works fine.

I think the recent changes introduced a breakage, on a fresh system:

```
panic: open /tmp/chatgpt-cli-last-session.json: no such file or directory
```

**Comment by akfaew** [comment]
Ah, I think I see it. I created an alias, and it has -c always set. But if there is no .json file, it will fail.

**Comment by edofic** [comment]
Didn't think of this use case. Yes, using `-c` on a first execution fails. Will make this into a warning instead of a hard error - I believe you still want to see something for the case when everything goes horribly wrong so there is a starting point for debugging.

**Comment by akfaew** [comment]
Would you consider this patch? It introduces a race condition, but should be fine:

```
diff --git a/.gitignore b/.gitignore
new file mode 100644
index 0000000..cd8d759
--- /dev/null
+++ b/.gitignore
@@ -0,0 +1 @@
+chatgpt-cli
diff --git a/main.go b/main.go
index 4b23b84..feb57f1 100644
--- a/main.go
+++ b/main.go
@@ -99,7 +99,8 @@ func getClient() *openai.Client {
 }
 
 func getCompletionRequest(p params, model string) openai.ChatCompletionRequest {
-       if p.continueSession {
+       _, err := os.Stat(sessionFile)
+       if p.continueSession && !os.IsNotExist(err) {
                return loadLastCompletion()
        } else {
                return newCompletionRequest(p, model)
```

**Comment by edofic** [comment]
Ugh sorry, missed this message and pushed my own changes. Thanks anyway

**Pull request closed without merging**
